### ISSUE TITLE
Upstream ?

### ISSUE THREAD

**Issue by pinage404** [0xc000022070/zen-browser-flake#1]
Hello,

What is preventing to upstream this to nixpkgs ?

**Comment by qouesm** [comment]
To my understanding, this flake is simply repacking the official binary release while the standards for nixpkgs is that it be built from source. See:
https://github.com/NixOS/nixpkgs/issues/327982#issuecomment-2301436730
https://github.com/NixOS/nixpkgs/pull/347222

**Comment by luisnquin** [comment]
Hello @pinage404, it's because builds from source are preferred over binaries from releases like in Zen browser and as @qouesm mentioned, there's still work in progress to package Zen to nixpkgs and this flake implementation doesn't contribute to achieve that goal.

Other reason why this will remain here is because sometimes people just wanna try the latest version of their browsers (see https://github.com/nix-community/flake-firefox-nightly).

Something I don't deny is to migrate this flake to https://github.com/nix-community, I think that it would be a great idea. I'll open a discussion in their forum to request the transfer of this repository to that place. :)

**Comment by luisnquin** [comment]
Btw, finally I decided to don't transfer this repository to nix-community.
